version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hagens-umbrel-glances_server_1
      APP_PORT: 61208
      PROXY_AUTH_ADD: "false"

  server:
    image: nicolargo/glances:3.4.0.3-full

    environment:
      - TZ=UTC
      - GLANCES_OPT=-w # Run Glances as a web server

    pid: host

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
